name: Expression Functions Demo

on: 
    push:
        branches:
          - main

jobs:
    expression-functions:
        runs-on: ubuntu-latest
        steps:
          - name: Check if String contains substring
            if: contains('Hello, world', 'llo')
            run: echo "The string contains the substring"
          - name: Check if string starts with 
            if: startsWith('Hello, World', 'He')  
            run: echo "The string starts with"
          - name: CHeck if string ends with
            if: endsWith('Hello, World', 'ld')  
            run: echo "The string ends with"
          - name: Format and echo string  
            run: echo ${{ format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat') }}
          - name:  Join issue lables
            if: github.event_name == 'issues'
            run: |
              echo "Issue lables: ${{ join(github.event_name.issue.lables.*.name, ',') }}"
          - name: Convert job context to JSON
            run: | 
              echo "Job context in JSON: ${{ toJSON(github.job) }}"
          - name: Hash files
            run: | 
              echo "{{ hashFiles('**/package-lock.json', '**/Gemfile.lock') }}"
          - name: The job has succesed
            if: ${{ success() }}
            run: echo "The job has finished Successfully"
          - name: The job has failed
            if: ${{ failure() }}
            run: echo "The job has not finished Successfully"

