name: "Dependent Jobs"

on: ['push']

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: 'Step 1'
        run: echo "This is from step 2"

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: 'Step 2'
        run: echo "This is from step 1"
